# coding=utf-8
import csv
import sqlite3
from prettytable import PrettyTable
from datetime import datetime

current_time = str(datetime.now().strftime('%Y_%m_%d_%H_%M_%S'))  # get current time for stamping

# reading the database generated by the labelling software
db = sqlite3.connect('D:\GitHub\Labeling-Backend\Application\lkydata.db')
cursor = db.cursor()
data = cursor.execute("SELECT * FROM attributes")  # select the values under attributes
rows = cursor.fetchall()

# display the database as a prettytable (aligned properly)
names = list(map(lambda x: x[0], cursor.description))   # listing the attribute names
pretty_db = PrettyTable(names)
pretty_db.align = 'l'
pretty_db.border = True

for entry in rows:
	pretty_db.add_row(entry)
	
print(str(pretty_db))

# save the database as a csv file for further application
with open('output_{0}.csv'.format(current_time), 'w') as csv_file:
	writer = csv.writer(csv_file, delimiter = ' ')
	writer.writerows(rows)
	
	csv_file.close()

# save the prettytable of attributes for viewing purposes
with open('attributes_table_{0}.txt'.format(current_time), 'w') as pt_file:
	table = pretty_db.get_string()
	pt_file.write(table)
	
	pt_file.close()